# Generated by Django 4.0.1 on 2022-01-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(default='', max_length=120)),
                ('numero1', models.CharField(default='', max_length=5)),
                ('numero2', models.CharField(default='', max_length=5)),
                ('numero3', models.CharField(default='', max_length=5)),
                ('numero4', models.CharField(default='', max_length=5)),
                ('numero5', models.CharField(default='', max_length=5)),
                ('numero6', models.CharField(default='', max_length=5)),
                ('numero7', models.CharField(default='', max_length=5)),
                ('numero8', models.CharField(default='', max_length=5)),
                ('numero9', models.CharField(default='', max_length=5)),
                ('numero10', models.CharField(default='', max_length=5)),
                ('numero11', models.CharField(default='', max_length=5)),
                ('numero12', models.CharField(default='', max_length=5)),
                ('numero13', models.CharField(default='', max_length=5)),
            ],
        ),
    ]
